[workspace]

members = [
    "smartpointer",
    "fearlessconcurrency",
    "designpatterns",
    "patternmatching",
    "variables",
    "ownership",
    "compoundtype",
    "traitgeneric",
    "macroadvance",
    "guess"
]

